### ISSUE TITLE
Some issues with strong name/sign app

### ISSUE THREAD

**Issue by JackCarterSmith** [hawezo/MojangSharp#3]
When using MojangSharp in a signed app, the build fail with this message : 
`System.IO.FileLoadException : 'Could not load file or assembly 'MojangSharp, Version=0.3.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'`
This seems to come during the digital signature of our application, I think that if the MojangSharp lib is not signed and we try to sign our application we get this error.

So I ask if MojangSharp is signed or not?

**Comment by innocenzi** [comment]
Hi, MojangSharp is not signed. You can [manually assign a strong name](https://blogs.msdn.microsoft.com/miah/2008/02/28/how-to-assign-a-strong-name-to-an-unsigned-3rd-party-assembly/) to MojangSharp or wait until I update it myself (likely next week).

**Comment by JackCarterSmith** [comment]
Thank ! I use manual assign strong name while waiting the next update :)

**Comment by innocenzi** [comment]
Hi, the [NuGet package](https://www.nuget.org/packages/Hawezo.MojangSharp/0.4.0) is now signed. If you can confirm that it now works for you, then I can close this ticket.

**Comment by innocenzi** [comment]
I'm closing the issue, assuming it's fixed.

**Comment by JackCarterSmith** [comment]
Yes I confirm (with a little late sorry...)
