### ISSUE TITLE
Add support for proxy ?

### ISSUE THREAD

**Issue by JackCarterSmith** [hawezo/MojangSharp#4]
Add support for proxy settings in the future ?

**Comment by innocenzi** [comment]
It could be a thing, although not planned at the moment.

**Comment by deeprobin** [comment]
A proxy feature is really nice. And the last commit is 10 months ago? If you want you can update this

**Comment by innocenzi** [comment]
Feel free to contribute, but I'm afraid I can't really work on this project at the moment.

**Comment by deeprobin** [comment]
@hawezo please close.

**Comment by innocenzi** [comment]
Likely fixed in #7.

**Comment by JackCarterSmith** [comment]
Thank you for the work!
