### ISSUE TITLE
Everything has stopped working

### ISSUE THREAD

**Issue by ghost** [hawezo/MojangSharp#6]
Everything stopped working ~ 2 months ago.

**Comment by innocenzi** [comment]
I'll take a look as soon as possible, I guess Mojang has updated Yggdrasil or changed how their API work. Thanks for letting me know!

**Comment by innocenzi** [comment]
If you encounter any issue with this again, feel free to open and provide more details on what is happening.

I fixed an issue with the UUID at time endpoint, with the authentication endpoint, and I added a way to check if your IP is secured (SecureIP endpoint). Please refer to the Sample program.
